substitutions:
  <<: !include common/substitutions_iot_base.yaml
  devicename: "meteo"
  upper_devicename: Meteo
  wifi_ip: "10.10.20.15"
  verze: "1.7" # Zde vzdy po editaci prepis verzi

esphome:
  name: $devicename
  project:
    name: "kulich.meteo"
    version: $verze

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

packages:
  wifi: !include common/config_wifi_iot_static_ip_meteo.yaml
  mqtt: !include common/mqtt_config_base_new.yaml
  #web_server: !include common/config_web_server.yaml

# --- Globalni promenne ---
globals:
# --- OTA s ochranou proti vypnuti WiFi behem nahravani ---
  - id: ota_active
    type: bool
    restore_value: no
    initial_value: "false"

# --- Globalni promenne pro uhrn srazek ---
  - id: _srazky_denni_akumulator
    type: float
    restore_value: no
    initial_value: "0.0"

  - id: _srazky_hod_akumulator
    type: float
    restore_value: no
    initial_value: "0.0"

  - id: _srazky_30min_akumulator
    type: float
    restore_value: no
    initial_value: "0.0"

  - id: _srazky_10min_akumulator
    type: float
    restore_value: no
    initial_value: "0.0"

ota:
  - platform: esphome
    password: !secret ota_password
    on_begin:
      then:
        - lambda: |-
            id(ota_active) = true;
        - wifi.enable
    on_end:
      then:
        - lambda: |-
            id(ota_active) = false;
    on_error:
      then:
        - lambda: |-
            id(ota_active) = false;
            
logger:
  level: WARN
  baud_rate: 0

time:
  - platform: sntp
    id: sntp_time
    servers: ${time_servers}
    timezone: ${time_zone}
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: |-
              id(_srazky_denni_akumulator) = 0;
          - component.update: srazky_za_den

      - seconds: 0
        minutes: 0
        then:
          - lambda: |-
              id(_srazky_hod_akumulator) = 0;
          - component.update: srazky_za_hodinu

      - seconds: 0
        minutes: /30
        then:
          - lambda: |-
              id(_srazky_30min_akumulator) = 0;
          - component.update: srazky_za_30min

      - seconds: 0
        minutes: /10
        then:
          - lambda: |-
              id(_srazky_10min_akumulator) = 0;
          - component.update: srazky_za_10min

# --- I2C napajeni pres GPIO3 (METEO Mini v3.5) ---
switch:
  - platform: gpio
    pin: GPIO3
    id: i2c_pwr
    restore_mode: ALWAYS_OFF

i2c:
  - sda: 19
    scl: 18
    scan: false

one_wire:
  - platform: gpio
    pin: 10


button:
  - <<: !include common/button/restart.yaml

text_sensor:
  - <<: !include common/text_sensor/wifi_ip.yaml
  - <<: !include common/text_sensor/version.yaml

  - platform: template
    name: "${upper_devicename} Smer vetru"
    id: wind_dir_card

  - platform: template
    name: "${upper_devicename} Vetrna stupnice"
    icon: "mdi:tailwind"
    id: wind_scale
    update_interval: never

  - platform: template
    name: "${upper_devicename} Vetrna stupnice kod"
    icon: "mdi:tailwind"
    id: wind_scale_code

binary_sensor:
  - platform: status
    name: "${upper_devicename} Online"
    id: dev_online

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml
  - <<: !include common/sensor/wifi_signal_procenta.yaml

  - platform: internal_temperature
    name: "CPU Teplota"
    update_interval: 300s

  # Teplota uvnitr krabicky s ESP
  - platform: dallas_temp
    address: 0x840416550c90ff28
    resolution: 10
    name: "${upper_devicename} Teplota ESP"
    update_interval: 300s

  # Napeti baterky (mer jen v mericim okynku)
  - platform: adc
    id: vcc_volt
    pin: 0
    name: "${upper_devicename} VCC Volt"
    attenuation: 12dB
    filters:
      - multiply: 1.7693877551
    update_interval: never

  # SHT4x (I2C) - meri se jen v okynku (napajeni pres GPIO3)
  - platform: sht4x
    id: sht4x_1
    address: 0x44
    update_interval: never
    temperature:
      name: "${upper_devicename} Teplota"
      id: sht_teplota
    humidity:
      name: "${upper_devicename} Vlhkost"
      id: sht_vlhkost

  - platform: template
    name: "${upper_devicename} Rosny bod"
    id: dew_point
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    lambda: |-
      const float a = 17.62;
      const float b = 243.12;
      float T = id(sht_teplota).state;
      float RH = id(sht_vlhkost).state;
      if (isnan(T) || isnan(RH) || RH <= 0) return NAN;
      float alpha = ((a * T) / (b + T)) + log(RH / 100.0);
      return (b * alpha) / (a - alpha);
    update_interval: 300s

  - platform: template
    name: "${upper_devicename} Absolutni vlhkost"
    id: abs_humidity
    unit_of_measurement: "g/m3"
    accuracy_decimals: 2
    lambda: |-
      float T = id(sht_teplota).state;
      float RH = id(sht_vlhkost).state;
      if (isnan(T) || isnan(RH)) return NAN;
      float svp = 6.112 * exp((17.62 * T) / (243.12 + T));
      float ah = 216.7 * ((RH / 100.0) * svp) / (273.15 + T);
      return ah;
    update_interval: 300s

  # BH1750 (I2C)
  - platform: bh1750
    id: illuminance
    name: "${upper_devicename} Svetelna intenzita"
    accuracy_decimals: 0
    address: 0x23
    update_interval: never

  # BMP280 (I2C)
  - platform: bmp280_i2c
    id: bmp280_1
    address: 0x77
    iir_filter: 4x
    update_interval: never
    temperature:
      name: "BMP280 Teplota"
      id: bmp280_teplota
      oversampling: 4x
    pressure:
      name: "BMP280 Tlak"
      id: bmp280_tlak
      oversampling: 4x

  - platform: template
    name: "Tlak na hladinu more"
    unit_of_measurement: "hPa"
    accuracy_decimals: 1
    lambda: |-
      const float P = id(bmp280_tlak).state;
      const float h = 277.0;
      const float T = id(bmp280_teplota).state;
      float sea = P * pow((1 - (0.0065 * h) / (T + 0.0065 * h + 273.15)), -5.257);
      return roundf(sea * 10) / 10.0;
    update_interval: 300s

  # --- Sekce rychlost vetru ---
  - platform: pulse_counter
    pin:
      number: GPIO5
      mode:
        input: true
        pulldown: true
    name: "${upper_devicename} Rychlost vetru"
    unit_of_measurement: "m/s"
    icon: "mdi:weather-windy"
    id: rychlost_vetru
    internal_filter: 13us
    update_interval: 10s
    filters:
      - multiply: 0.005560619
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6

  - platform: copy
    name: "${upper_devicename} Prumerna rychlost vetru"
    icon: "mdi:weather-windy"
    id: wind_speed_avg
    source_id: rychlost_vetru
    unit_of_measurement: "m/s"
    filters:
      - throttle_average: 60s

  - platform: copy
    name: "${upper_devicename} Rychlost vetru (km/h)"
    id: wind_speed_kmh
    source_id: rychlost_vetru
    unit_of_measurement: "km/h"
    icon: "mdi:weather-windy"
    filters:
      - multiply: 3.6

  - platform: copy
    name: "${upper_devicename} Prumerna rychlost vetru (km/h)"
    icon: "mdi:weather-windy"
    id: wind_speed_kmh_avg
    source_id: wind_speed_avg
    unit_of_measurement: "km/h"
    filters:
      - multiply: 3.6
      - throttle_average: 60s
    on_value:
      lambda: |-
        if (x < 1) { id(wind_scale_code).publish_state("0");  id(wind_scale).publish_state("Bezvetri"); }
        else if (x < 6) { id(wind_scale_code).publish_state("1");  id(wind_scale).publish_state("Vanek"); }
        else if (x < 12) { id(wind_scale_code).publish_state("2"); id(wind_scale).publish_state("Slaby vitr"); }
        else if (x < 20) { id(wind_scale_code).publish_state("3"); id(wind_scale).publish_state("Mirny vitr"); }
        else if (x < 29) { id(wind_scale_code).publish_state("4"); id(wind_scale).publish_state("Dosti cerstvy vitr"); }
        else if (x < 39) { id(wind_scale_code).publish_state("5"); id(wind_scale).publish_state("Cerstvy vitr"); }
        else if (x < 50) { id(wind_scale_code).publish_state("6"); id(wind_scale).publish_state("Silny vitr"); }
        else if (x < 62) { id(wind_scale_code).publish_state("7"); id(wind_scale).publish_state("Prudky vitr"); }
        else if (x < 75) { id(wind_scale_code).publish_state("8"); id(wind_scale).publish_state("Bourlivy vitr"); }
        else if (x < 89) { id(wind_scale_code).publish_state("9"); id(wind_scale).publish_state("Vichrice"); }
        else if (x < 103) { id(wind_scale_code).publish_state("10"); id(wind_scale).publish_state("Silna vichrice"); }
        else if (x < 118) { id(wind_scale_code).publish_state("11"); id(wind_scale).publish_state("Mohutna vichrice"); }
        else { id(wind_scale_code).publish_state("12"); id(wind_scale).publish_state("Orkan"); }

  # --- Sekce smer vetru ---
  - platform: adc
    pin: GPIO1
    id: adc_smer_vetru
    internal: true
    update_interval: 120s
    accuracy_decimals: 3

  - platform: resistance
    sensor: adc_smer_vetru
    id: resistance_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm
    internal: true
    name: "Odporovy senzor"
    accuracy_decimals: 1
    filters:
      - heartbeat: 120s
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 3100
              below: 3300
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "S"
            - sensor.template.publish:
                id: wind_heading
                state: 0.0

      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 700
              below: 900
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SV"
            - sensor.template.publish:
                id: wind_heading
                state: 45.0

      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 70
              below: 180
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "V"
            - sensor.template.publish:
                id: wind_heading
                state: 90.0

      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 190
              below: 300
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "JV"
            - sensor.template.publish:
                id: wind_heading
                state: 135.0

      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 320
              below: 600
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "J"
            - sensor.template.publish:
                id: wind_heading
                state: 180.0

      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 1400
              below: 1800
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "JZ"
            - sensor.template.publish:
                id: wind_heading
                state: 225.0

      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 3310
              below: 3600
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "Z"
            - sensor.template.publish:
                id: wind_heading
                state: 270.0

      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 1950
              below: 2300
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SZ"
            - sensor.template.publish:
                id: wind_heading
                state: 315.0

  - platform: template
    name: "${upper_devicename} Smer vetru (stupne)"
    id: wind_heading
    unit_of_measurement: "deg"

  # --- Sekce srazkomer ---
  - platform: pulse_counter
    pin:
      number: GPIO4
      mode:
        input: true
        pulldown: true
    unit_of_measurement: "mm"
    name: "${upper_devicename} Srazkomer"
    icon: "mdi:weather-rainy"
    id: srazko_mer
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 13us
    update_interval: 60s
    filters:
      - multiply: 0.25
    accuracy_decimals: 4

  - platform: copy
    id: srazky_za_min
    name: "${upper_devicename} Srazky za min"
    source_id: srazko_mer
    unit_of_measurement: "mm"
    accuracy_decimals: 4
    filters:
      - delta: 0.0001

  - platform: template
    name: "${upper_devicename} Srazky za 30 min"
    id: srazky_za_30min
    unit_of_measurement: "mm"
    icon: "mdi:weather-rainy"
    accuracy_decimals: 2
    lambda: |-
      return id(_srazky_30min_akumulator);
    update_interval: 60s

  - platform: template
    name: "${upper_devicename} Srazky za 10 min"
    id: srazky_za_10min
    unit_of_measurement: "mm"
    icon: "mdi:weather-rainy"
    accuracy_decimals: 2
    lambda: |-
      return id(_srazky_10min_akumulator);
    update_interval: 60s

  - platform: template
    name: "${upper_devicename} Srazky za hod"
    id: srazky_za_hodinu
    unit_of_measurement: "mm"
    icon: "mdi:weather-rainy"
    accuracy_decimals: 2
    lambda: |-
      return id(_srazky_hod_akumulator);
    update_interval: 60s

  - platform: template
    name: "${upper_devicename} Srazky za den"
    id: srazky_za_den
    unit_of_measurement: "mm"
    icon: "mdi:weather-rainy"
    accuracy_decimals: 2
    lambda: |-
      return id(_srazky_denni_akumulator);
    update_interval: 60s

# --- Pricitani srazek kazdou minutu (nechat, kvuli akumulatorum) ---
interval:
  - interval: 60s
    then:
      - lambda: |-
          float srazka = id(srazky_za_min).state;
          id(_srazky_denni_akumulator) += srazka;
          id(_srazky_hod_akumulator) += srazka;
          id(_srazky_30min_akumulator) += srazka;
          id(_srazky_10min_akumulator) += srazka;

  # --- Merici a odesilaci okynko (baterka) ---
  # Uprav si interval podle potreby (napr. 5min / 10min)
  - interval: 5min
    then:
      - switch.turn_on: i2c_pwr
      - delay: 300ms
      - component.update: sht4x_1
      - component.update: illuminance
      - component.update: bmp280_1
      - component.update: vcc_volt
      - delay: 1s
      - switch.turn_off: i2c_pwr

  - interval: 10min
    then:
      - if:
          condition:
            and:
              - lambda: "return id(ota_active) == false;"
              - not:
                  binary_sensor.is_on: dev_online
          then:
            - logger.log: "Offline too long, rebooting"
            - button.press: restart_button


# smer vetru
# GPIO1 - Modra
# smer -- ADC Volt
# Sever -- N -- 3132Ω -- 0.79v
# Severo_Vychod -- NE -- 1643Ω -- 0.47v
# Vychod -- E -- 292Ω -- 0.10v
# Jiho_Vychod -- SE -- 602Ω -- 0.19v
# Jih -- S -- 974Ω -- 0.29v
# Jiho_Zapad -- SW -- 2372Ω -- 0.63v
# Zapad -- W -- 3997Ω -- 0.94v
# Severo_Zapad -- NW -- 3657Ω -- 0.88v

# rychlost vetru
# pin: GPIO5 - Zelena

# srazkomer
# pin: GPIO4 - Seda

# 3v3 - Oranzova
# GND - Zluta

# Dalass
# pin: 10
